"""initial schema

Revision ID: d948eb8fb032
Revises: 
Create Date: 2026-09-29 05:01:42.761357
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'd948eb8fb032'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.String(length=32), nullable=True),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('case_id', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_at', 'audit_logs', ['action', 'at'], unique=False)
    op.create_index('ix_audit_actor_at', 'audit_logs', ['actor', 'at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_table('backups',
    sa.Column('backup_type', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('errors',
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('case_id', sa.String(length=32), nullable=True),
    sa.Column('submission_id', sa.String(length=32), nullable=True),
    sa.Column('operator', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_errors_case_id'), 'errors', ['case_id'], unique=False)
    op.create_index('ix_errors_category_at', 'errors', ['category', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_errors_session_id'), 'errors', ['session_id'], unique=False)
    op.create_table('explanation_templates',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=False),
    sa.Column('requested_review', sa.Text(), nullable=False),
    sa.Column('reference', sa.Text(), nullable=False),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_explanation_templates_reason_code'), 'explanation_templates', ['reason_code'], unique=False)
    op.create_table('exports',
    sa.Column('export_type', sa.String(length=32), nullable=False),
    sa.Column('fmt', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=True),
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker', sa.String(length=64), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_category', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_status_created', 'jobs', ['status', 'created_at'], unique=False)
    op.create_table('proxies',
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('secret_ref', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host', 'port', 'protocol', name='uq_proxy_endpoint')
    )
    op.create_table('reasons',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('policy_reference', sa.String(length=255), nullable=True),
    sa.Column('default_explanation_template', sa.Text(), nullable=True),
    sa.Column('official_channel_hint', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_reason_code_version')
    )
    op.create_index(op.f('ix_reasons_code'), 'reasons', ['code'], unique=False)
    op.create_table('targets',
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_telegram_id'), 'targets', ['telegram_id'], unique=False)
    op.create_index('ix_targets_type_status', 'targets', ['target_type', 'status'], unique=False)
    op.create_index(op.f('ix_targets_url'), 'targets', ['url'], unique=False)
    op.create_index(op.f('ix_targets_username'), 'targets', ['username'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('accounts',
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('phone_masked', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('proxy_id', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_telegram_id'), 'accounts', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=False)
    op.create_table('cases',
    sa.Column('case_number', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('reason_id', sa.String(length=32), nullable=True),
    sa.Column('template_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('legal_basis', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=128), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_operator', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('draft_json', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reason_id'], ['reasons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['explanation_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index(op.f('ix_cases_assigned_operator'), 'cases', ['assigned_operator'], unique=False)
    op.create_index(op.f('ix_cases_reason_id'), 'cases', ['reason_id'], unique=False)
    op.create_index(op.f('ix_cases_reference_number'), 'cases', ['reference_number'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index('ix_cases_status_priority', 'cases', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_cases_target_id'), 'cases', ['target_id'], unique=False)
    op.create_table('session_groups',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('proxy_id', sa.String(length=32), nullable=True),
    sa.Column('check_concurrency', sa.Integer(), nullable=True),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('case_events',
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_case_events_case_created', 'case_events', ['case_id', 'created_at'], unique=False)
    op.create_table('evidence',
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=True),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('external_url', sa.String(length=1024), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_by', sa.String(length=64), nullable=True),
    sa.Column('integrity_ok', sa.Boolean(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_case_type', 'evidence', ['case_id', 'evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_sha256'), 'evidence', ['sha256'], unique=False)
    op.create_table('sessions',
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_format', sa.String(length=32), nullable=True),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=16), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=True),
    sa.Column('group_id', sa.String(length=32), nullable=True),
    sa.Column('proxy_id', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('phone_masked', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('health', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_category', sa.String(length=32), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('check_count', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Float(), nullable=False),
    sa.Column('rate_limited_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['session_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path', name='uq_sessions_file_path')
    )
    op.create_index(op.f('ix_sessions_account_id'), 'sessions', ['account_id'], unique=False)
    op.create_index(op.f('ix_sessions_file_name'), 'sessions', ['file_name'], unique=False)
    op.create_index(op.f('ix_sessions_group_id'), 'sessions', ['group_id'], unique=False)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_index('ix_sessions_status_location', 'sessions', ['status', 'location'], unique=False)
    op.create_index(op.f('ix_sessions_telegram_id'), 'sessions', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_sessions_username'), 'sessions', ['username'], unique=False)
    op.create_table('submissions',
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('operator', sa.String(length=64), nullable=True),
    sa.Column('package_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=128), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_submissions_case_status', 'submissions', ['case_id', 'status'], unique=False)
    op.create_index(op.f('ix_submissions_reference_number'), 'submissions', ['reference_number'], unique=False)
    op.create_table('evidence_custody',
    sa.Column('evidence_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sha256_at_time', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_custody_evidence_id'), 'evidence_custody', ['evidence_id'], unique=False)
    op.create_table('responses',
    sa.Column('submission_id', sa.String(length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('reference_number', sa.String(length=128), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responses_submission_id'), 'responses', ['submission_id'], unique=False)
    op.create_table('session_checks',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('operator', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_status', sa.String(length=32), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_category', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('server_wait_seconds', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_checks_session_started', 'session_checks', ['session_id', 'started_at'], unique=False)
    op.create_table('submission_attempts',
    sa.Column('submission_id', sa.String(length=32), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('operator', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_attempts_submission_id'), 'submission_attempts', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_attempts_submission_id'), table_name='submission_attempts')
    op.drop_table('submission_attempts')
    op.drop_index('ix_session_checks_session_started', table_name='session_checks')
    op.drop_table('session_checks')
    op.drop_index(op.f('ix_responses_submission_id'), table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_evidence_custody_evidence_id'), table_name='evidence_custody')
    op.drop_table('evidence_custody')
    op.drop_index(op.f('ix_submissions_reference_number'), table_name='submissions')
    op.drop_index('ix_submissions_case_status', table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_sessions_username'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_telegram_id'), table_name='sessions')
    op.drop_index('ix_sessions_status_location', table_name='sessions')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_group_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_file_name'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_account_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_evidence_sha256'), table_name='evidence')
    op.drop_index('ix_evidence_case_type', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_case_events_case_created', table_name='case_events')
    op.drop_table('case_events')
    op.drop_table('session_groups')
    op.drop_index(op.f('ix_cases_target_id'), table_name='cases')
    op.drop_index('ix_cases_status_priority', table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_reference_number'), table_name='cases')
    op.drop_index(op.f('ix_cases_reason_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_operator'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_telegram_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_targets_username'), table_name='targets')
    op.drop_index(op.f('ix_targets_url'), table_name='targets')
    op.drop_index('ix_targets_type_status', table_name='targets')
    op.drop_index(op.f('ix_targets_telegram_id'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_reasons_code'), table_name='reasons')
    op.drop_table('reasons')
    op.drop_table('proxies')
    op.drop_index('ix_jobs_status_created', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('exports')
    op.drop_index(op.f('ix_explanation_templates_reason_code'), table_name='explanation_templates')
    op.drop_table('explanation_templates')
    op.drop_index(op.f('ix_errors_session_id'), table_name='errors')
    op.drop_index('ix_errors_category_at', table_name='errors')
    op.drop_index(op.f('ix_errors_case_id'), table_name='errors')
    op.drop_table('errors')
    op.drop_table('backups')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index('ix_audit_actor_at', table_name='audit_logs')
    op.drop_index('ix_audit_action_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
