// Generate app/web/templates/partials/icons.html from lucide-static (ISC license).
// Usage: node scripts/gen_icons.mjs <path-to-node_modules> <output-file>
// Called by scripts/build_assets.sh. The output is committed; do not edit it by hand.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const [, , nodeModules, outFile] = process.argv;
if (!nodeModules || !outFile) {
  console.error("usage: node gen_icons.mjs <node_modules> <out.html>");
  process.exit(2);
}

// Every icon the dashboard uses. Add a name here, then re-run scripts/build_assets.sh.
const ICONS = [
  "layout-dashboard", "key-round", "users", "network", "crosshair", "briefcase", "send", "triangle-alert",
  "scroll-text", "chart-column", "settings", "log-out", "sun", "moon", "languages", "search", "filter", "plus",
  "refresh-cw", "scan-search", "shield-check", "activity", "check", "x", "chevron-left", "chevron-right",
  "arrow-right", "arrow-left", "file-text", "download", "upload", "lock", "user", "eye", "eye-off", "clock",
  "database", "server", "cpu", "hard-drive", "gauge", "layers", "sparkles", "fingerprint", "globe", "menu",
  "circle-check", "circle-alert", "octagon-x", "hourglass", "archive", "file-down", "badge-check", "link",
  "hash", "mail", "zap", "history", "list-checks", "shield", "folder-open", "scale", "radar", "paperclip",
  "inbox", "trending-up", "circle-dot", "power", "power-off", "shield-alert",
];

const entries = ICONS.map((name) => {
  const svg = readFileSync(join(nodeModules, "lucide-static", "icons", `${name}.svg`), "utf8");
  const inner = svg
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>[\s\S]*$/, "")
    .replace(/\s*\n\s*/g, "")
    .trim();
  if (!inner) throw new Error(`empty icon body: ${name}`);
  return `  '${name}': '${inner.replace(/'/g, "\\'")}'`;
});

const out = `{# Generated by scripts/build_assets.sh from lucide-static v0.460.0 (ISC). Do not edit by hand. #}
{% set _ICONS = {
${entries.join(",\n")}
} %}
{% macro icon(name, cls='icon') -%}
<svg class="{{ cls }}" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">{{ _ICONS.get(name, '')|safe }}</svg>
{%- endmacro %}
`;
writeFileSync(outFile, out);
console.log(`icons: ${ICONS.length} written to ${outFile}`);
