"""Write a local .env with fresh random secrets and a SQLite database.

Standard library only, so it runs before the virtualenv has any packages. Never overwrites an existing .env.
Used by the run_windows.bat / run_local.sh launchers, but safe to run directly:

    python scripts/make_env.py
    python scripts/make_env.py --database-url postgresql+asyncpg://user:pass@localhost:5432/tglegal
"""
from __future__ import annotations

import argparse
import base64
import secrets
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def build(database_url: str) -> str:
    app_secret = secrets.token_urlsafe(48)
    # Fernet key: 32 random bytes, url-safe base64 (matches app/security/session_crypto.py).
    session_key = base64.urlsafe_b64encode(secrets.token_bytes(32)).decode()
    return f"""# Generated by scripts/make_env.py. Keep this file private; it holds this install's secrets.
APP_ENV=local
APP_DEBUG=false
APP_SECRET_KEY={app_secret}

# Local database. SQLite needs no server. To use PostgreSQL instead, replace this line, e.g.:
#   DATABASE_URL=postgresql+asyncpg://tglegal:tglegal@localhost:5432/tglegal
DATABASE_URL={database_url}

# Encrypts session files at rest. Losing this key makes existing encrypted .session files unreadable.
SESSION_FILE_ENCRYPTION_KEY={session_key}

SESSIONS_ROOT=./sessions
EVIDENCE_ROOT=./evidence_store
BACKUP_ROOT=./backups
EXPORT_ROOT=./exports

# Default provider does not connect to Telegram. For real checks (connect, confirm the session is authorised,
# disconnect) set TELEGRAM_PROVIDER=telethon and your own API ID / hash from https://my.telegram.org, then remove
# the leading '# ' from the two lines below.
TELEGRAM_PROVIDER=simulation
# TELEGRAM_API_ID=123456
# TELEGRAM_API_HASH=0123456789abcdef0123456789abcdef

# Official-email submission stays off until you enable it and configure a mailbox you are authorised to use.
# Example (Gmail with an app password): remove the leading '# ' and fill in your address.
SUBMISSION_EMAIL_ENABLED=false
# SMTP_HOST=smtp.gmail.com
# SMTP_PORT=587
# SMTP_USER=you@gmail.com
# SMTP_PASSWORD=your-16-character-app-password
# SMTP_FROM=you@gmail.com
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--database-url", default="sqlite+aiosqlite:///./data/tglegal.db")
    ap.add_argument("--force", action="store_true", help="overwrite an existing .env")
    args = ap.parse_args()
    dest = ROOT / ".env"
    if dest.exists() and not args.force:
        print(f".env already exists at {dest} — leaving it unchanged.")
        return
    (ROOT / "data").mkdir(exist_ok=True)
    dest.write_text(build(args.database_url), encoding="utf-8")
    print(f"Wrote {dest}")


if __name__ == "__main__":
    main()
